package io.miret.etienne.registre.common.passkey

import kotlinx.serialization.Serializable

/**
 * Options sent to the browser to initiate a passkey authentication ceremony.
 *
 * Corresponds to the WebAuthn `PublicKeyCredentialRequestOptions` dictionary.
 *
 * @property challenge Base64URL-encoded random challenge generated by the
 *    server.
 * @property rpId The relying party identifier the credential must be scoped to.
 * @property allowCredentials Credentials the user may authenticate with.
 * @property userVerification User verification requirement.
 * @property timeout Milliseconds the browser should wait before the operation
 *    times out.
 */
@Serializable
data class AuthenticationOptions(
  val challenge: String,
  val rpId: String,
  val allowCredentials: List<AllowedCredential>,
  val userVerification: UserVerification,
  val timeout: Int,
)
