package io.miret.etienne.registre.common.passkey

import io.miret.etienne.registre.common.User
import kotlinx.serialization.Serializable

/**
 * Options sent to the browser to initiate a passkey registration ceremony.
 *
 * Corresponds to the WebAuthn `PublicKeyCredentialCreationOptions` dictionary.
 *
 * @property challenge Base64URL-encoded random challenge generated by the
 *    server.
 * @property rp Information about the relying party.
 * @property user The user account to associate with the new credential.
 * @property pubKeyCredParams Ordered list of supported public key types and
 *    signing algorithms.
 * @property timeout Milliseconds the browser should wait before the operation
 *    times out.
 * @property attestation Attestation conveyance preference: `"none"`,
 *    `"indirect"`, or `"direct"`.
 * @property authenticatorSelection Criteria used to select a suitable
 *    authenticator.
 */
@Serializable
data class RegistrationOptions(
  val challenge: String,
  val rp: RpInfo,
  val user: User,
  val pubKeyCredParams: List<PubKeyCredParam>,
  val timeout: Long,
  val attestation: String,
  val authenticatorSelection: AuthenticatorSelection,
)
