import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { signIn, useSession } from 'next-auth/react'
import { JSX } from 'preact';

const Home: NextPage = () => {
  const {data: session} = useSession ();
  let greeting: JSX.Element;
  if (session) {
    greeting = <p>Hello {session.user?.email}!</p>;
  } else {
    greeting = <p>Please <button onClick={() => signIn()}>log in</button>.</p>;
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        {greeting}
      </div>
  );
}

export default Home
