import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { getSession, signOut } from 'next-auth/react'
import { Session } from 'next-auth';
import Header from '../components/header';

interface HomeParams {
  session: Session
}

const Home: NextPage<HomeParams> = ({session}) => {

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Header/>
        <p>Hello {session.user?.email}!</p>
        <p><button onClick={() => signOut()}>Se déconnecter</button></p>
      </div>
  );
}

export async function getServerSideProps (context: NextPageContext) {
  const session = await getSession (context);
  if (session === null) {
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false
      }
    }
  }

  return {
    props: {session}
  };
}

export default Home;
